name: Trigger auto deployment for mycontainerappnew

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Docckerfile/**'
    - '.github/workflows/mycontainerappnew-AutoDeployTrigger-c1ec458f-57a0-45d9-9739-f12786821760.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYCONTAINERAPPNEW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYCONTAINERAPPNEW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYCONTAINERAPPNEW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Docckerfile 
          registryUrl: containerappregs.azurecr.io
          registryUsername: ${{ secrets.MYCONTAINERAPPNEW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPPNEW_REGISTRY_PASSWORD }}
          containerAppName: mycontainerappnew
          resourceGroup: ACARG
          imageToBuild: containerappregs.azurecr.io/mycontainerappnew:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


